import { Product } from '@/src/types';

export const PRODUCTS: Product[] = [
  {
    id: 'artic-01',
    slug: 'collection-arctic-01',
    name: 'Collection Arctic 01™',
    price: 899.99,
    originalPrice: 1100.00,
    image: '/assets/images/puffer_hero_1780990255920.png',
    gallery: [
      '/assets/images/puffer_hero_1780990255920.png',
      '/assets/images/puffer_aurora_1780990270336.png',
      '/assets/images/puffer_stealth_1780990299665.png',
    ],
    category: 'puffers',
    colors: ['Silver', 'White', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Fully armored technical mountain puffer. Engineered to withstand temperature drops down to -40°C. Finished with a hyper-gloss silver chrome element shield, thermal insulation layers, and integrated goggles-retaining harness loops.',
    specifications: [
      'Integrated double-walled heat locks',
      'DWR 20,000mm waterproofing dynamic shield',
      'Detachable utility storm hood with goggle-slits',
      'Double-insulated lining with graphene conductors',
    ],
    rating: 4.9,
    reviewsCount: 312,
    badge: 'HERO EDITION',
    stock: 25,
    material: 'Graphene Composite',
    temperature: '-40°C and below',
    weather: 'Extreme Cold',
    featured: true,
  },
  {
    id: 'aurora-01',
    slug: 'aurora-cold-shield',
    name: 'Aurora Cold Shield™',
    price: 1999.00,
    originalPrice: 2200.00,
    image: '/assets/images/puffer_aurora_1780990270336.png',
    category: 'puffers',
    colors: ['White', 'Blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'An elite oversized winter fortress. Tailored using premium high-loft goose down encased in durable ultra-light micro-ripstop nylon, featuring side access ventilation.',
    specifications: [
      'Heavy insulated ergonomic collar block',
      'Magnetic thermal quick-closures',
      'Reinforced articulated elbow patches',
      'Graphene heat diffusion matrix',
    ],
    rating: 5.0,
    reviewsCount: 84,
    badge: 'NEW RELEASE',
    stock: 12,
    material: 'Goose Down',
    temperature: '-30°C to -20°C',
    weather: 'Blizzard',
    featured: true,
    new: true,
  },
  {
    id: 'orbit-01',
    slug: 'orbit-gloss-shield',
    name: 'Orbit Gloss Shield',
    price: 1299.99,
    image: '/assets/images/puffer_orbit_1780990285645.png',
    category: 'puffers',
    colors: ['Silver', 'Black'],
    sizes: ['M', 'L', 'XL'],
    description: 'High-gloss platinum-coated protective layer. Deflects cold wind, freezing rain, and high arctic blizzards.',
    specifications: [
      'High-sheen reflective platinum outer lining',
      'Dual-stage internal ventilation zippers',
      'Sealed seams with silicone protection lines',
      'Hypoallergenic goose-down fill (900-fill power)',
    ],
    rating: 4.8,
    reviewsCount: 154,
    badge: 'HIGH GLOSS',
    stock: 8,
    material: 'Platinum Coated Nylon',
    temperature: '-20°C to -10°C',
    weather: 'Snow',
  },
  {
    id: 'stealth-01',
    slug: 'stealth-shadow-puffer',
    name: 'Stealth Shadow Puffer',
    price: 1199.99,
    image: '/assets/images/puffer_stealth_1780990299665.png',
    category: 'puffers',
    colors: ['Black', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Low-profile, tactical cold insulation deck. Featuring composite carbon-fiber shell reinforcement and multi-pocket utility strapping grids.',
    specifications: [
      'Matte black anti-reflective compound weave',
      'Six multi-point internal and external tech pockets',
      'Removable storm-flap with fleece lining',
      'Quick-release emergency release harness system',
    ],
    rating: 4.9,
    reviewsCount: 201,
    badge: 'BESTSELLER',
    stock: 30,
    material: 'Carbon Fiber',
    temperature: '-30°C to -20°C',
    weather: 'Wind',
  },
  {
    id: 'glacier-01',
    slug: 'glacier-tactile-shield',
    name: 'Glacier Tactile Shield',
    price: 999.99,
    originalPrice: 1050.00,
    image: '/assets/images/puffer_glacier_1780990314070.png',
    category: 'puffers',
    colors: ['Blue', 'White', 'Black'],
    sizes: ['S', 'M', 'L'],
    description: 'Arctic-exploration ready down coat, with modular temperature controls and hybrid honeycomb down grids.',
    specifications: [
      'Hybrid fleece-and-down core construction',
      'Abrasion-resistant shoulder and pocket overlays',
      'Thumbhole wind-cuffs with soft Lycra layers',
      'Integrated pocket heater wiring hookups',
    ],
    rating: 4.7,
    reviewsCount: 118,
    badge: 'EXPLORER',
    stock: 15,
    material: 'Polartec',
    temperature: '-20°C to -10°C',
    weather: 'Mixed',
  },
  {
    id: 'tundra-boots',
    slug: 'tundra-coldgrav-boots',
    name: 'Tundra ColdGrav Boots',
    price: 499.00,
    originalPrice: 550.00,
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&q=80&w=600&h=600',
    category: 'boots',
    colors: ['Black', 'Silver'],
    sizes: ['7', '8', '9', '10', '11'],
    description: 'All-terrain gravity boots featuring high-traction vibram soles, heat locks, and steel-core security wraps.',
    specifications: [
      'Vibram arctic grip ultra traction soles',
      'Aerogel isolated sole-plate protection',
      'Steel-braided reinforcement cables',
      'Double waterproof membrane shell',
    ],
    rating: 4.9,
    reviewsCount: 92,
    badge: 'EXCLUSIVE',
    stock: 20,
    material: 'Vibram Rubber',
    temperature: '-30°C to -20°C',
    weather: 'Snow',
  },
  {
    id: 'fissure-boots',
    slug: 'fissure-coldrail-boot',
    name: 'Fissure ColdRail Boot',
    price: 589.00,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=600&h=600',
    category: 'boots',
    colors: ['White', 'Black'],
    sizes: ['8', '9', '10', '11'],
    description: 'Fully high-altitude integrated compression snow boots built with quick-tightening rotor cables.',
    specifications: [
      'Dual-zone Boa coil fit cord system',
      'Rechargeable thermal active insoles',
      'Waterproof armored rubber shell overlay',
      'Hypersoft heel rebound comfort cells',
    ],
    rating: 4.8,
    reviewsCount: 46,
    stock: 10,
    material: 'Vibram Rubber',
    temperature: '-20°C to -10°C',
    weather: 'Mixed',
  },
  {
    id: 'fusion-goggles',
    slug: 'orbital-fusion-goggles',
    name: 'Orbital Fusion Goggles',
    price: 299.00,
    originalPrice: 350.00,
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&q=80&w=600&h=600',
    category: 'gear',
    colors: ['Silver', 'Black', 'Blue'],
    sizes: ['ONE SIZE'],
    description: 'Sleek geometric weather-deflection goggles with electromagnetic anti-fog lenses.',
    specifications: [
      'Chromashift UV active tint system',
      'Magnetic switch lens release points',
      'Triple layer responsive foam facepad',
      'Extreme weather anti-fog dual flow vents',
    ],
    rating: 4.9,
    reviewsCount: 180,
    badge: 'ESSENTIAL',
    stock: 45,
    material: 'Polycarbonate',
    weather: 'Mixed',
  },
  {
    id: 'thermo-gloves',
    slug: 'thermal-shield-gloves',
    name: 'Thermal Shield Gloves',
    price: 189.00,
    image: 'https://images.unsplash.com/photo-1543330091-27228394c7dc?auto=format&fit=crop&q=80&w=600&h=600',
    category: 'gear',
    colors: ['Black'],
    sizes: ['S', 'M', 'L'],
    description: 'Heated gloves with composite carbon fiber knuckles and tactile fingertip tech overlay.',
    specifications: [
      'Conductive smart touchscreen tips',
      'Rechargeable dual micro-lithium cells',
      'High-grain synthetic goat skin palm grip',
      'Impact-resistant carbon knuckle plates',
    ],
    rating: 4.6,
    reviewsCount: 64,
    stock: 35,
    material: 'Carbon Fiber',
    temperature: '-10°C to 0°C',
    weather: 'Cold',
  },
];

export const COLLECTIONS = [
  {
    id: 'arctic-01',
    slug: 'arctic-01',
    name: 'Arctic 01',
    description: 'The flagship collection. Engineered for the absolute extremes of the polar regions.',
    image: '/assets/images/puffer_mountain_1780990327549.png',
    featured: true,
    season: 'Winter 2026',
    year: '2026',
    productIds: ['artic-01', 'aurora-01'],
  },
  {
    id: 'stealth-line',
    slug: 'stealth-line',
    name: 'Stealth Line',
    description: 'Low-profile tactical operations. Blacked out, carbon reinforced, mission ready.',
    image: '/assets/images/puffer_stealth_1780990299665.png',
    featured: true,
    season: 'Winter 2026',
    year: '2026',
    productIds: ['stealth-01', 'tundra-boots'],
  },
  {
    id: 'glacier-pro',
    slug: 'glacier-pro',
    name: 'Glacier Pro',
    description: 'Professional grade alpine exploration gear. Tested at 6000m+ elevations.',
    image: '/assets/images/puffer_glacier_1780990314070.png',
    featured: true,
    season: 'Winter 2026',
    year: '2026',
    productIds: ['glacier-01', 'fissure-boots', 'thermo-gloves'],
  },
];

export const JOURNAL_ARTICLES = [
  {
    id: 'post-1',
    title: 'The Science of Cold: How Graphene is Revolutionizing Thermal Protection',
    slug: 'science-of-cold-graphene',
    excerpt: 'Exploring the cutting-edge material science behind graphene-infused insulation and its impact on extreme weather performance gear.',
    content: '',
    image: '/assets/images/puffer_mountain_1780990327549.png',
    category: 'Technology',
    author: {
      name: 'Kai Nakamura',
      role: 'Head of Materials Science',
    },
    publishedAt: '2026-06-01',
    readTime: 8,
    tags: ['graphene', 'technology', 'materials', 'innovation'],
    featured: true,
  },
  {
    id: 'post-2',
    slug: 'arctic-field-test-arctic-01',
    title: 'Field Test: Arctic 01 at -45°C in Svalbard',
    excerpt: 'Our team spent 72 hours in the High Arctic testing the Arctic 01 prototype in extreme conditions.',
    content: '',
    image: '/assets/images/puffer_hero_1780990255920.png',
    category: 'Field Tests',
    author: {
      name: 'Sofia Berg',
      role: 'Lead Field Tester',
    },
    publishedAt: '2026-05-15',
    readTime: 12,
    tags: ['field-test', 'arctic-01', 'svalbard', 'extreme'],
    featured: true,
  },
  {
    id: 'post-3',
    slug: 'design-philosophy-form-follows-function',
    title: 'Design Philosophy: Where Form Follows Function in Extreme Conditions',
    excerpt: 'Behind the design decisions that make CHRONO STATIC gear both beautiful and brutally functional.',
    content: '',
    image: '/assets/images/puffer_aurora_1780990270336.png',
    category: 'Design',
    author: {
      name: 'Marcus Chen',
      role: 'Creative Director',
    },
    publishedAt: '2026-04-28',
    readTime: 6,
    tags: ['design', 'philosophy', 'minimalism'],
    featured: false,
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Products', slug: 'all' },
  { id: 'puffers', label: 'Puffers', slug: 'puffers' },
  { id: 'boots', label: 'Boots', slug: 'boots' },
  { id: 'gear', label: 'Gear', slug: 'gear' },
  { id: 'accessories', label: 'Accessories', slug: 'accessories' },
];